
# - hosts: apache
#   remote_user: jane 
#   become : yes
- name: Apache
  hosts: proxy
  become: yes
  vars:
    users: 
      - Eren

  tasks:
    - name: run echo command
      command: /bin/echo hello world

    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: Upgrade System
      apt: 
        upgrade: dist 
        update_cache: yes

    - name: apache2 listen on port 80
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 80" state=present
      notify:
        - restart apache2

    - name: apache2 virtualhost on port 443
      lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:443>" line="<VirtualHost *:443>" state=present
      notify:
        - restart apache2


  