- name: web servers
  hosts: web
  become_method: sudo
  remote_user: yoan
  become: yes
  tasks: 
    - name: git install
      apt:
        # mode: "0600"
        name: git
        state: latest
        update_cache: true

    - name: Install sudo
      apt: 
        name: sudo
        state: latest
    
     
    - name: "Install Python 3.6"
      apt: 
        name: python3.6
        state: latest

    - name: "Install python-apt"
      apt: 
        name: python-apt
        state: latest

    - name: "Install bash"
      apt: 
        name: bash
        state: latest


    - name: création de user
      user:
        name: Eren
        state: present
        password: "{{ 'Eren' | password_hash('sha512') }}"  

    - name: ajouter un utilisateur
      user:
        shell: /usr/sbin/nologin
        name: toto

