- name: web servers
  hosts: webapp
  become: yes
  vars:
    users: 
      - Eren
  tasks: 
    - name: git install
      apt:
        # mode: "0600"
        name: git
        state: latest
        update_cache: true

    - name: Install sudo
      apt: 
        name: sudo
        state: latest
    
     
    - name: "Install Python 3.6"
      apt: 
        name: python3.6
        state: latest

    - name: "Install python-apt"
      apt: 
        name: python-apt
        state: latest

    - name: "Install bash"
      apt: 
        name: bash
        state: latest


    - name: création de user
      user:
        name: "{{ item }}"
        groups: sudo, root
        shell: /bin/bash
        generate_ssh_key: yes  
        append: no
      loop: "{{ users }}"


    - name: "Prend le dossier source sur ma vm ou se situe la clef pu, le copie sur ma machine hôte"
      ansible.builtin.fetch:
        src: /home/Eren/.ssh/id_rsa.pub
        dest: /home/shadowsleaders/
        flat: yes

    - name: "take autorized_key in file"
      ansible.posix.authorized_key:
        user: "{{ item }}"
        state: present
        key: "{{ lookup('file', '/home/shadowsleaders/id_rsa.pub') }}"
      loop: "{{ users }}"
  


    # - name: myalias
    #   copy:
    #     src: /bashrc/alias
    #     dest: "/home/{{ item }}/.bash_aliases"
    #     force: yes
    #     mode: 0664
    #     whith_items: "{{ user }}"
    

